In [1]:
import numpy as np
import pandas as pd
from numpy import array
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error

In [16]:
population_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/world_population.csv', index_col='Country Code')
meta_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/metadata.csv', index_col='Country Code')

In [20]:
a=meta_df['Income Group']
a=pd.DataFrame(a) 
a.reset_index(inplace=True)
a

Country Code         Income Group
0            ABW          High income
1            AFG           Low income
2            AGO  Lower middle income
3            ALB  Upper middle income
4            AND          High income
..           ...                  ...
212          XKX  Lower middle income
213          YEM           Low income
214          ZAF  Upper middle income
215          ZMB  Lower middle income
216          ZWE           Low income

[217 rows x 2 columns]

In [19]:
population_df

1960        1961        1962        1963        1964  \
Country Code                                                               
ABW              54211.0     55438.0     56225.0     56695.0     57032.0   
AFG            8996351.0   9166764.0   9345868.0   9533954.0   9731361.0   
AGO            5643182.0   5753024.0   5866061.0   5980417.0   6093321.0   
ALB            1608800.0   1659800.0   1711319.0   1762621.0   1814135.0   
AND              13411.0     14375.0     15370.0     16412.0     17469.0   
...                  ...         ...         ...         ...         ...   
XKX             947000.0    966000.0    994000.0   1022000.0   1050000.0   
YEM            5172135.0   5260501.0   5351799.0   5446063.0   5543339.0   
ZAF           17456855.0  17920673.0  18401608.0  18899275.0  19412975.0   
ZMB            3044846.0   3140264.0   3240587.0   3345145.0   3452942.0   
ZWE            3747369.0   3870756.0   3999419.0   4132756.0   4269863.0   

                    1965        1966        1967        1968        1969  ...  \
Country Code                                                              ...   
ABW              57360.0     57715.0     58055.0     58386.0     58726.0  ...   
AFG            9938414.0  10152331.0  10372630.0  10604346.0  10854428.0  ...   
AGO            6203299.0   6309770.0   6414995.0   6523791.0   6642632.0  ...   
ALB            1864791.0   1914573.0   1965598.0   2022272.0   2081695.0  ...   
AND              18549.0     19647.0     20758.0     21890.0     23058.0  ...   
...                  ...         ...         ...         ...         ...  ...   
XKX            1078000.0   1106000.0   1135000.0   1163000.0   1191000.0  ...   
YEM            5643643.0   5748588.0   5858638.0   5971407.0   6083619.0  ...   
ZAF           19942303.0  20486439.0  21045785.0  21622590.0  22219897.0  ...   
ZMB            3563407.0   3676189.0   3791887.0   3912085.0   4038923.0  ...   
ZWE            4410212.0   4553433.0   4700041.0   4851431.0   5009514.0  ...   

                    2008        2009        2010        2011        2012  \
Country Code                                                               
ABW             101353.0    101453.0    101669.0    102053.0    102577.0   
AFG           27294031.0  28004331.0  28803167.0  29708599.0  30696958.0   
AGO           21759420.0  22549547.0  23369131.0  24218565.0  25096150.0   
ALB            2947314.0   2927519.0   2913021.0   2905195.0   2900401.0   
AND              83861.0     84462.0     84449.0     83751.0     82431.0   
...                  ...         ...         ...         ...         ...   
XKX            1747383.0   1761474.0   1775680.0   1791000.0   1805200.0   
YEM           22356391.0  22974929.0  23606779.0  24252206.0  24909969.0   
ZAF           50412129.0  50970818.0  51584663.0  52263516.0  52998213.0   
ZMB           13082517.0  13456417.0  13850033.0  14264756.0  14699937.0   
ZWE           13558469.0  13810599.0  14086317.0  14386649.0  14710826.0   

                    2013        2014        2015        2016        2017  
Country Code                                                              
ABW             103187.0    103795.0    104341.0    104822.0    105264.0  
AFG           31731688.0  32758020.0  33736494.0  34656032.0  35530081.0  
AGO           25998340.0  26920466.0  27859305.0  28813463.0  29784193.0  
ALB            2895092.0   2889104.0   2880703.0   2876101.0   2873457.0  
AND              80788.0     79223.0     78014.0     77281.0     76965.0  
...                  ...         ...         ...         ...         ...  
XKX            1824100.0   1821800.0   1801800.0   1816200.0   1830700.0  
YEM           25576322.0  26246327.0  26916207.0  27584213.0  28250420.0  
ZAF           53767396.0  54539571.0  55291225.0  56015473.0  56717156.0  
ZMB           15153210.0  15620974.0  16100587.0  16591390.0  17094130.0  
ZWE           15054506.0  15411675.0  15777451.0  16150362.0  16529904.0  

[217 rows x 

In [21]:
population_df.reset_index(inplace=True)


In [22]:
population_df

Country Code        1960        1961        1962        1963        1964  \
0            ABW     54211.0     55438.0     56225.0     56695.0     57032.0   
1            AFG   8996351.0   9166764.0   9345868.0   9533954.0   9731361.0   
2            AGO   5643182.0   5753024.0   5866061.0   5980417.0   6093321.0   
3            ALB   1608800.0   1659800.0   1711319.0   1762621.0   1814135.0   
4            AND     13411.0     14375.0     15370.0     16412.0     17469.0   
..           ...         ...         ...         ...         ...         ...   
212          XKX    947000.0    966000.0    994000.0   1022000.0   1050000.0   
213          YEM   5172135.0   5260501.0   5351799.0   5446063.0   5543339.0   
214          ZAF  17456855.0  17920673.0  18401608.0  18899275.0  19412975.0   
215          ZMB   3044846.0   3140264.0   3240587.0   3345145.0   3452942.0   
216          ZWE   3747369.0   3870756.0   3999419.0   4132756.0   4269863.0   

           1965        1966        1967        1968  ...        2008  \
0       57360.0     57715.0     58055.0     58386.0  ...    101353.0   
1     9938414.0  10152331.0  10372630.0  10604346.0  ...  27294031.0   
2     6203299.0   6309770.0   6414995.0   6523791.0  ...  21759420.0   
3     1864791.0   1914573.0   1965598.0   2022272.0  ...   2947314.0   
4       18549.0     19647.0     20758.0     21890.0  ...     83861.0   
..          ...         ...         ...         ...  ...         ...   
212   1078000.0   1106000.0   1135000.0   1163000.0  ...   1747383.0   
213   5643643.0   5748588.0   5858638.0   5971407.0  ...  22356391.0   
214  19942303.0  20486439.0  21045785.0  21622590.0  ...  50412129.0   
215   3563407.0   3676189.0   3791887.0   3912085.0  ...  13082517.0   
216   4410212.0   4553433.0   4700041.0   4851431.0  ...  13558469.0   

           2009        2010        2011        2012        2013        2014  \
0      101453.0    101669.0    102053.0    102577.0    103187.0    103795.0   
1    28004331.0  28803167.0  29708599.0  30696958.0  31731688.0  32758020.0   
2    22549547.0  23369131.0  24218565.0  25096150.0  25998340.0  26920466.0   
3     2927519.0   2913021.0   2905195.0   2900401.0   2895092.0   2889104.0   
4       84462.0     84449.0     83751.0     82431.0     80788.0     79223.0   
..          ...         ...         ...         ...         ...         ...   
212   1761474.0   1775680.0   1791000.0   1805200.0   1824100.0   1821800.0   
213  22974929.0  23606779.0  24252206.0  24909969.0  25576322.0  26246327.0   
214  50970818.0  51584663.0  52263516.0  52998213.0  53767396.0  54539571.0   
215  13456417.0  13850033.0  14264756.0  14699937.0  15153210.0  15620974.0   
216  13810599.0  14086317.0  14386649.0  14710826.0  15054506.0  15411675.0   

           2015        2016        2017  
0      104341.0    104822.0    105264.0  
1    33736494.0  34656032.0  35530081.0  
2    27859305.0  28813463.0  29784193.0  
3     2880703.0   2876101.0   2873457.0  
4       78014.0     77281.0     76965.0  
..          ...         ...         ...  
212   1801800.0   1816200.0   1830700.0  
213  26916207.0  27584213.0  28250420.0  
214  55291225.0  56015473.0  56717156.0  
215  16100587.0  16591390.0  17094130.0  
216  15777451.0  16150362.0  16529904.0  

[217 rows x 59 columns]

In [23]:
merged= pd.merge(a, population_df, left_on='Country Code', 
                    right_on='Country Code', how='left')

In [24]:
merged

Country Code         Income Group        1960        1961        1962  \
0            ABW          High income     54211.0     55438.0     56225.0   
1            AFG           Low income   8996351.0   9166764.0   9345868.0   
2            AGO  Lower middle income   5643182.0   5753024.0   5866061.0   
3            ALB  Upper middle income   1608800.0   1659800.0   1711319.0   
4            AND          High income     13411.0     14375.0     15370.0   
..           ...                  ...         ...         ...         ...   
212          XKX  Lower middle income    947000.0    966000.0    994000.0   
213          YEM           Low income   5172135.0   5260501.0   5351799.0   
214          ZAF  Upper middle income  17456855.0  17920673.0  18401608.0   
215          ZMB  Lower middle income   3044846.0   3140264.0   3240587.0   
216          ZWE           Low income   3747369.0   3870756.0   3999419.0   

           1963        1964        1965        1966        1967  ...  \
0       56695.0     57032.0     57360.0     57715.0     58055.0  ...   
1     9533954.0   9731361.0   9938414.0  10152331.0  10372630.0  ...   
2     5980417.0   6093321.0   6203299.0   6309770.0   6414995.0  ...   
3     1762621.0   1814135.0   1864791.0   1914573.0   1965598.0  ...   
4       16412.0     17469.0     18549.0     19647.0     20758.0  ...   
..          ...         ...         ...         ...         ...  ...   
212   1022000.0   1050000.0   1078000.0   1106000.0   1135000.0  ...   
213   5446063.0   5543339.0   5643643.0   5748588.0   5858638.0  ...   
214  18899275.0  19412975.0  19942303.0  20486439.0  21045785.0  ...   
215   3345145.0   3452942.0   3563407.0   3676189.0   3791887.0  ...   
216   4132756.0   4269863.0   4410212.0   4553433.0   4700041.0  ...   

           2008        2009        2010        2011        2012        2013  \
0      101353.0    101453.0    101669.0    102053.0    102577.0    103187.0   
1    27294031.0  28004331.0  28803167.0  29708599.0  30696958.0  31731688.0   
2    21759420.0  22549547.0  23369131.0  24218565.0  25096150.0  25998340.0   
3     2947314.0   2927519.0   2913021.0   2905195.0   2900401.0   2895092.0   
4       83861.0     84462.0     84449.0     83751.0     82431.0     80788.0   
..          ...         ...         ...         ...         ...         ...   
212   1747383.0   1761474.0   1775680.0   1791000.0   1805200.0   1824100.0   
213  22356391.0  22974929.0  23606779.0  24252206.0  24909969.0  25576322.0   
214  50412129.0  50970818.0  51584663.0  52263516.0  52998213.0  53767396.0   
215  13082517.0  13456417.0  13850033.0  14264756.0  14699937.0  15153210.0   
216  13558469.0  13810599.0  14086317.0  14386649.0  14710826.0  15054506.0   

           2014        2015        2016        2017  
0      103795.0    104341.0    104822.0    105264.0  
1    32758020.0  33736494.0  34656032.0  35530081.0  
2    26920466.0  27859305.0  28813463.0  29784193.0  
3     2889104.0   2880703.0   2876101.0   2873457.0  
4       79223.0     78014.0     77281.0     76965.0  
..          ...         ...         ...         ...  
212   1821800.0   1801800.0   1816200.0   1830700.0  
213  26246327.0  26916207.0  27584213.0  28250420.0  
214  54539571.0  55291225.0  56015473.0  56717156.0  
215  15620974.0  16100587.0  16591390.0  17094130.0  
216  15411675.0  15777451.0  16150362.0  16529904.0  

[217 rows x 60 columns]

In [32]:
taf= merged[merged['Income Group']=='High income']

In [34]:
check = taf.sum()
check= pd.DataFrame(check)

In [35]:
check.reset_index(inplace=True)

In [39]:
[[     1960, 166502848],[     1961, 170210778],
       [     1962, 174013498],
       [     1963, 177950312],
       [     1984, 182077594],
       [     193a5, 186434685],
       [     1966, 191035377],
       [     1967, 195863148],
       [     1968, 200890086],
       [     1969, 206074326],
       [     1970, 211385069],
       [     1971, 216814959],
       [     1972, 222372305],
       [     1973, 228060405],
       [     1974, 233887209],
       [     1975, 239859140],
       [     1976, 245986989],
       [     1977, 252271835],
       [     1978, 258700456],
       [     1979, 265253926],
       [     1980, 271925904],
       [     1981, 278716283],
       [     1982, 285653497],
       [     1983, 292795982],
       [     1984, 300220347],
       [     1985, 307987034],
       [     1986, 316105719],
       [     1987, 324577008],
       [     1988, 333438165],
       [     1989, 342729958],
       [     1990, 352473181],
       [     1991, 362705618],
       [     1992, 373402947],
       [     1993, 384447813],
       [     1994, 395678396],
       [     1995, 406983803],
       [     1996, 418317960],
       [     1997, 429730581],
       [     1998, 441325367],
       [     1999, 453254723],
       [     2000, 465631330],
       [     2001, 478477973],
       [     2002, 491764952],
       [     2003, 505488618],
       [     2004, 519630935],
       [     2005, 534172627],
       [     2006, 549135479],
       [     2007, 564514253],
       [     2008, 580229110],
       [     2009, 596172925],
       [     2010, 612274687],
       [     2011, 628504663],
       [     2012, 640340917],
       [     2013, 656899625],
       [     2014, 673826031],
       [     2015, 691211477],
       [     2016, 709067648],
       [     2017, 727379727]]

In [177]:
data=[[     1960, 166502848],[     1961, 170210778],
       [     1962, 174013498],
       [     1963, 177950312],
       [     1964, 182077594],
       [     1965, 186434685],
       [     1966, 191035377],
       [     1967, 195863148],
       [     1968, 200890086],
       [     1969, 206074326],
       [     1970, 211385069],
       [     1971, 216814959],
       [     1972, 222372305],
       [     1973, 228060405],
       [     1974, 233887209],
       [     1975, 239859140],
       [     1976, 245986989],
       [     1977, 252271835],
       [     1978, 258700456],
       [     1979, 265253926],
       [     1980, 271925904],
       [     1981, 278716283],
       [     1982, 285653497],
       [     1983, 292795982],
       [     1984, 300220347],
       [     1985, 307987034],
       [     1986, 316105719],
       [     1987, 324577008],
       [     1988, 333438165],
       [     1989, 342729958],
       [     1990, 352473181],
       [     1991, 362705618],
       [     1992, 373402947],
       [     1993, 384447813],
       [     1994, 395678396],
       [     1995, 406983803],
       [     1996, 418317960],
       [     1997, 429730581],
       [     1998, 441325367],
       [     1999, 453254723],
       [     2000, 465631330],
       [     2001, 478477973],
       [     2002, 491764952],
       [     2003, 505488618],
       [     2004, 519630935],
       [     2005, 534172627],
       [     2006, 549135479],
       [     2007, 564514253],
       [     2008, 580229110],
       [     2009, 596172925],
       [     2010, 612274687],
       [     2011, 628504663],
       [     2012, 640340917],
       [     2013, 656899625],
       [     2014, 673826031],
       [     2015, 691211477],
       [     2016, 709067648],
       [     2017, 727379727]]

In [203]:
def sklearn_kfold_split(data,K):
    X= data[:,0]
    y=data[:,1]
    kf = KFold(n_splits=K)
    kf.get_n_splits(X)
    #print(kf)
    for train_index, test_index in kf.split(X,y):
        print( train_index, test_index)
  


In [204]:
sklearn_kfold_split(data,4)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57] [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 44 45 46 47 48 49 50 51 52 53 54 55 56 57] [30 31 32 33 34 35 36 37 38 39 40 41 42 43]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43] [44 45 46 47 48 49 50 51 52 53 54 55 56 57]


In [180]:
X=a[:,0]
y=a[:,1]

In [183]:
data=np.array(data)
data

array([[     1960, 166502848],
       [     1961, 170210778],
       [     1962, 174013498],
       [     1963, 177950312],
       [     1964, 182077594],
       [     1965, 186434685],
       [     1966, 191035377],
       [     1967, 195863148],
       [     1968, 200890086],
       [     1969, 206074326],
       [     1970, 211385069],
       [     1971, 216814959],
       [     1972, 222372305],
       [     1973, 228060405],
       [     1974, 233887209],
       [     1975, 239859140],
       [     1976, 245986989],
       [     1977, 252271835],
       [     1978, 258700456],
       [     1979, 265253926],
       [     1980, 271925904],
       [     1981, 278716283],
       [     1982, 285653497],
       [     1983, 292795982],
       [     1984, 300220347],
       [     1985, 307987034],
       [     1986, 316105719],
       [     1987, 324577008],
       [     1988, 333438165],
       [     1989, 342729958],
       [     1990, 352473181],
       [     1991, 362705618],
       [

In [108]:
data[:,1]

array([166502848, 170210778, 174013498, 177950312, 182077594, 186434685,
       191035377, 195863148, 200890086, 206074326, 211385069, 216814959,
       222372305, 228060405, 233887209, 239859140, 245986989, 252271835,
       258700456, 265253926, 271925904, 278716283, 285653497, 292795982,
       300220347, 307987034, 316105719, 324577008, 333438165, 342729958,
       352473181, 362705618, 373402947, 384447813, 395678396, 406983803,
       418317960, 429730581, 441325367, 453254723, 465631330, 478477973,
       491764952, 505488618, 519630935, 534172627, 549135479, 564514253,
       580229110, 596172925, 612274687, 628504663, 640340917, 656899625,
       673826031, 691211477, 709067648, 727379727])

In [137]:
(array([4,5,5]))

array([4, 5, 5])

In [167]:
X

array([1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970,
       1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981,
       1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992,
       1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017])

In [170]:
kf = KFold(n_splits=4)
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [171]:
kf.split(X,y)

<generator object _BaseKFold.split at 0x00EBD7F0>